---
experiment:
  name: aogn-czsl/utzappos50k
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: AOGN
  dropout: true
  norm: true
  relu: true
  obj_fclayers: 2
  obj_emb: [ 2048,512 ]
  attr_fclayers: 2
  attr_emb: [ 2048,512 ]
  emb_dim: 300
  emb_init: word2vec
  image_extractor: ViT
  train_only: true
  open_world: false
training:
  batch_size: 128
  eval_val_every: 1
  load:
  lr: 0.00002
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  max_epochs: 30
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: true
  freeze_features: false
vit:
  obj_nlayer: 4
  attr_nlayer: 4
  obj_nhead: 10
  attr_nhead: 10

